services:
  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_LOCATION}/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DATA_LOCATION}/certs:/etc/certs
    networks:
      - internal_only
      - external_access
    environment:
      CF_API_EMAIL: ${CLOUDFLARE_EMAIL}
      CF_DNS_API_TOKEN: ${CLOUDFLARE_TOKEN}
      CF_ZONE_API_TOKEN: ${CLOUDFLARE_TOKEN}

networks:
  external_access:
    external: true
  internal_only:
    external: true
