
networks:
  internal_only:
    external: true

services:
  postgresql:
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    networks:
      - internal_only
    volumes:
    - database:/var/lib/postgresql/data
  authentik-server:
    command: server
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik-rtr.rule=Host(`authentik.${BASE_DOMAIN}`)
      - traefik.http.routers.authentik-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.authentik-rtr.entrypoints=https
      - traefik.http.services.authentik-svc.loadbalancer.server.port=9000
      - traefik.http.services.authentik-svc.loadbalancer.server.scheme=http
      - "traefik.http.routers.authentik-output-rtr.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.${BASE_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - serverstransport.insecureskipverify=true
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'

    networks:
      - internal_only
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ghcr.io/goauthentik/server:2026.2.1
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ${DATA_LOCATION}/data:/data
    - ${DATA_LOCATION}/custom-templates:/templates

  worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'

    networks:
      - internal_only
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ghcr.io/goauthentik/server:2026.2.1
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DATA_LOCATION}/data:/data
    - ${DATA_LOCATION}/certs:/certs
    - ${DATA_LOCATION}/custom-templates:/templates

volumes:
  database:
    driver: local
