services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    dns: ${DNS_SERVER}
    labels: 
      - traefik.enable=true
      - traefik.http.routers.backrest.rule=Host(`backrest.${BASE_DOMAIN}`)
      - traefik.http.routers.backrest.tls.certresolver=letsencrypt
      - traefik.http.routers.backrest.entrypoints=https
      - traefik.http.services.backrest.loadbalancer.server.port=9898
      - traefik.http.services.backrest.loadbalancer.server.scheme=http
      - serverstransport.insecureskipverify=true
      - homepage.group=Admin
      - homepage.name=Backrest
      - homepage.icon=backrest.png
      - homepage.href=https://backrest.dc404.uk/
      - homepage.description=Backups

    volumes:
      - /data/backrest/data:/data
      - /data/backrest/config:/config
      - /data/backrest/cache:/cache
      - /data/backrest/tmp:/tmp
      - /data/backrest/rclone:/root/.config/rclone
      - /backups:/backups
      - /data:/ext-data

      # Env files to backup

      - ../actual/.env:/ext-repo/actual/.env
      - ../authentik/.env:/ext-repo/authentik/.env
      - ../backrest/.env:/ext-repo/backrest/.env
      - ../homepage/.env:/ext-repo/homepage/.env
      - ../immich/.env:/ext-repo/immich/.env
      - ../mealie/.env:/ext-repo//mealie/.env
      - ../paperless/.env:/ext-repo/paperless/.env
      - ../pihole/.env:/ext-repo/pihole/.env
      - ../tailscale/.env:/ext-repo//tailscale/.env
      - ../traefik/.env:/ext-repo/traefik/.env
      - ../trilium/.env:/ext-repo/trilium/.env
      

    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    restart: unless-stopped
    networks:
      - external_access
      - internal_only

networks:
  external_access:
    external: true
  internal_only:
      external: true
