services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    dns: ${DNS_SERVER}
    labels: 
      - traefik.enable=true
      - traefik.http.routers.backrest.rule=Host(`backrest.${BASE_DOMAIN}`)
      - traefik.http.routers.backrest.tls.certresolver=letsencrypt
      - traefik.http.routers.backrest.entrypoints=https
      - traefik.http.services.backrest.loadbalancer.server.port=9898
      - traefik.http.services.backrest.loadbalancer.server.scheme=http
      - serverstransport.insecureskipverify=true

    volumes:
      - /data/backrest/data:/data
      - /data/backrest/config:/config
      - /data/backrest/cache:/cache
      - /data/backrest/tmp:/tmp
      - /data/backrest/rclone:/root/.config/rclone
      - /backups:/backups
      - /data:/ext-data
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    restart: unless-stopped
    networks:
      - internal_only

networks:
  internal_only:
      external: true
