name: trilium

services:

  trilium-server:
    image: triliumnext/trilium:latest
    restart: always
    container_name: trilium
    hostname: trilium
    volumes:
      - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal_only
    labels:
      - traefik.enable=true
      - traefik.http.routers.trilium.rule=Host(`trilium.${BASE_DOMAIN}`)
      - traefik.http.routers.trilium.tls.certresolver=letsencrypt
      - traefik.http.routers.trilium.entrypoints=https
      - traefik.http.services.trilium.loadbalancer.server.port=8080
      - traefik.http.services.trilium.loadbalancer.server.scheme=http
      - serverstransport.insecureskipverify=true
      - homepage.group=Documents
      - homepage.name=Trilium
      - homepage.icon=triliumnext.png
      - homepage.href=https://trilium.dc404.uk/
      - homepage.description=General notes and Wiki

networks:
  internal_only:
    external: true
