services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:sts
    restart: always
    networks:
      - proxy_access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    name: portainer_data

networks:
  proxy_access:
    external: true
